### ISSUE TITLE
TooManySuits Compatibility [Fixed]

### ISSUE THREAD

**Issue by TNephilim** [Hexnet111/SuitSaver#1]
Not an issue exactly but more of a request. I have too many suits installed so me and my friends can have more variety of suits and pages to select them. But the issue is suit saver only saves the first tab and doesn't save any outfit from tabs 2 and onward.

I know this isn't this or the other creators problem but if it's possible to make it compatible I hope you will consider

**Comment by Hexnet111** [comment]
> Not an issue exactly but more of a request. I have too many suits installed so me and my friends can have more variety of suits and pages to select them. But the issue is suit saver only saves the first tab and doesn't save any outfit from tabs 2 and onward.
> 
> I know this isn't this or the other creators problem but if it's possible to make it compatible I hope you will consider

I will look into it pretty soon, and see if I can do something about it. Thanks for letting me know!

**Comment by Hexnet111** [comment]
Fixed this issue! Let me know if you have anymore things in mind! :)
Will leave this open for another day or 2 incase something pops up in the new version. You're also welcome to close the issue yourself.

**Comment by Hexnet111** [comment]
Seems like there is an issue with syncing across clients. Will look for a potential fix tomorrow morning.

**Comment by Hexnet111** [comment]
Morning arrived early! Issue should be fully fixed now 😅

**Comment by TNephilim** [comment]
> Morning arrived early! Issue should be fully fixed now 😅

Oh nice! I haven't had a chance to play with my friends the past two days. But I think I can test it tomorrow night. I am sure it works great though
